import { Metadata } from "next";

export const siteConfig = {
  name: "Ora Browser",
  shortName: "Ora",
  description:
    "Built on WebKit, designed for macOS. Ora delivers a clean, native experience that's simple, powerful, and free of bloat.",
  url: "https://orabrowser.com",
  ogImage: "/opengraph-image.png",
  creator: "@orabrowser",
  keywords: [
    "Ora Browser",
    "macOS browser",
    "WebKit browser",
    "native macOS browser",
    "SwiftUI browser",
    "fast browser",
    "secure browser",
    "beautiful browser",
    "minimal browser",
    "clean browser",
    "privacy-first browsing",
    "distraction-free browsing",
    "native experience",
    "tab management",
    "content blocker",
    "Safari alternative",
    "macOS native app",
    "Arc alternative",
    "Arc browser alternative",
    "better than Arc",
    "Arc replacement",
    "Zen alternative",
    "Zen browser alternative",
    "better than Zen",
    "Zen replacement",
    "Dia alternative",
    "Dia browser alternative",
    "better than Dia",
    "Dia replacement",
    "Brave alternative",
    "Chrome alternative",
    "SigmaOS alternative",
    "Firefox alternative",
    "Edge alternative",
    "Vivaldi alternative",
    "Opera alternative",
    "modern browser alternative",
    "productivity browser alternative",
    "aesthetic browser alternative",
  ],
};

// Simple structured data for single-page site
export function createWebsiteSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: siteConfig.name,
    url: siteConfig.url,
    description: siteConfig.description,
  };
}

export function createSoftwareApplicationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: siteConfig.name,
    applicationCategory: "BrowserApplication",
    operatingSystem: "macOS 14.0+",
    description: siteConfig.description,
    url: siteConfig.url,
    downloadUrl: "https://github.com/the-ora/browser/releases",
    softwareVersion: "0.1.8",
    license: "https://opensource.org/licenses/MIT",
    isAccessibleForFree: true,
    author: {
      "@type": "Organization",
      name: "The Ora Team",
      url: "https://github.com/the-ora",
    },
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
    },
    softwareRequirements: "macOS 14.0 or later, Xcode 15 or later",
    codeRepository: "https://github.com/the-ora/browser",
    programmingLanguage: ["Swift", "SwiftUI"],
    featureList: [
      "Native macOS UI built with SwiftUI/AppKit",
      "Fast, responsive browsing powered by WebKit",
      "Privacy-first browsing with built-in ad blocker and tracking prevention",
      "Vertical tabs with sidebar navigation",
      "Tab management with containers (spaces) and pinning",
      "Split view for side-by-side browsing",
      "Floating tab switcher",
      "Session restore after app restart or crash",
      "Quick Launcher for instant navigation and search",
      "Picture in Picture support",
      "Developer tools and web inspector",
      "Multiple search engine support",
      "Keyboard shortcuts for power users",
      "Open source and MIT licensed",
    ],
    aggregateRating: {
      "@type": "AggregateRating",
      ratingValue: "5",
      ratingCount: "1",
    },
  };
}
